version: '3.4'
services:
  node-api:
    container_name: node-api
    image: node:lts
    working_dir: /var/www/html/app/
    entrypoint: /bin/bash
    ports:
      - 3000:3000
    volumes:
      - ./lilian-node/:/var/www/html/app
    tty: true
  vue-frontend:
    container_name: vue-frontend
    image: node:lts
    working_dir: /var/www/html/app/
    entrypoint: /bin/bash
    ports:
      - 8080:8080
    volumes:
      - ./lilian-front/:/var/www/html/app
    tty: true
    depends_on:
      - node-api
