const logo = new TypeIt("#typing")
  .type("SOLER Lilian")
  .pause(1000)
  .delete()
  .type("Platforme pour élèves")
  .pause(1000)
  .delete()
  .type("Developpeur Web")
  .pause(1000)
  .delete()
  .type("Entreprise Didelo")
  .pause(1000)
  .delete()
  .type("SOLER Lilian")
  .go();

